language: node_js
node_js:
- iojs
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_1fd1fd30be03_key -iv $encrypted_1fd1fd30be03_iv
  -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)";
     echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list;
     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -;
     sudo apt-get update && sudo apt-get -y install google-cloud-sdk;
     exec -l $SHELL;
  fi
- gcloud auth activate-service-account --key-file gcloud-service-key.json
- gcloud config set project shift-dms-183315
after_success:
- gcloud compute instances stop ci-instance-4 --zone=us-east1-b
- gcloud compute instances start ci-instance-4 --zone=us-east1-b
